## Exercise 1: Write a function that checks whether a given graph is connected or not.

A graph $G=(S,A)$ is said to be connected if for any pair of vertices $(u,v)$ there is a path connecting $u$ and $v$. 
- Example 1: Oriented graph

![orientedgraph](data/oriented-graph.png)

    - The graph above is connected because we can find a path between each pair of vertices
    - The pairs of vertices are: $(1,2)$, $(1,3)$, $(1,4)$, $(1,5)$, $(2,3)$, $(2,4)$, $(2,5)$, $(3,2)$, $(3,4)$, $(3,5)$, $(4,5)$.
    
- Example 2: Unoriented graph

![unorientedgraph](data/unoriented-graph.png)

    - The graph above is not connected because we cannot find a path between the vertices (5,6) and the other vertices. 
    - This graph is composed of two connected components.

In [26]:
import numpy as np
m=np.array([[0,0,0,0,0],[0,0,1,0,1],[0,1,0,1,0],[0,0,1,0,1],[0,1,0,1,0]])
print(m)
t=[]
print(m.shape)
for i in range(m.shape[0]):
    for j in range(m.shape[1]):
        if m[i,j]==1:
            t.append((i,j))
print(t)   
        
      

[[0 0 0 0 0]
 [0 0 1 0 1]
 [0 1 0 1 0]
 [0 0 1 0 1]
 [0 1 0 1 0]]
(5, 5)
[(1, 2), (1, 4), (2, 1), (2, 3), (3, 2), (3, 4), (4, 1), (4, 3)]


## Exercise 2: Given a binary tree, find the sum of all the leaves.

![Tree1](data/tree1.png)

- Example: 

```python
>>> a = [40, [14, [5, [3, [], []], [2, [], []] ], [4, [], [] ]], [6, [1, [], []], [5, [], []]]]
>>> print(somme_feuilles(a3))
```

In [32]:
import numpy as np
def somme_leaves(tree): 
    a=0
    for key , value in tree.items():
        if isinstance(value, dict):
            a+=somme_leaves(value)
        else:
            a+= int(key)
    return a
             

            
graph={'40':{'6':{'5':0,'1':0},'14':{'4':0,'5':0}}}
print(somme_leaves(graph))

            



 
 
    

15


## Exercise 3: Given a binary tree, check whether all leaves are at the same level or not.

![Tree2](data/tree2.png)

- Expected output:

```python
>>> same_level(T1) 
False
>>> same_level(T2)
True
```