## Exercise 1: Hamming distance

Write a `hamming()` function that calculates the Hamming distance between two words when they have the same length, and returns −1 otherwise.

- Indication:

    The Hamming distance between two vectors is simply the sum of corresponding elements that differ between the vectors.

    - For example, suppose we have the following two vectors:
    ```python
    x = [1, 2, 3, 4]
    y = [1, 2, 5, 7]
    ```
    - The Hamming distance between the two vectors would be 2, since this is the total number of corresponding elements that have different values.


### 

In [11]:
def calculate(l,h):
    if len(l)!=len(h):
        return -1
    
    if len(l)==len(h):
        a=0
        for i in range(len(l)):
             
            if l[i]!=h[i]:
                a+=1
        return a
l = ['soy','sirius','rigel']
h = ['soy','planet','rigel']
g=calculate(l,h)
print(g)

    
    
                
                    
            
        

1


## Exercise 2: Syracuse sequence

We define the Syracuse sequence ($u_n$) by $u_0$ $\in$ $\mathbb{N}$ and

$$
u_n + 1 = \left\{
    \begin{array}{ll}
        \frac{u_n}{2} \mbox{ if $u_n$ is even} \\
        3u_{n+1} \mbox{ if $u_n$ is odd} 
    \end{array}
\right.
$$

1. Write a `syracuse()` function which takes as input two integers $u_0$ and $n$ and returns $u_n$.
2. Check that we always end up with cycle $4,2,1,4,2,1,\dots$, for $0 \leq u_0 \leq 20$.
3. Given u_0 $\in$ $\mathbb{N}$ denote $h$ the smallest of the integers $n$ such that $u_n = 1$ (we assume that such $h$ exists).
    - Write a function `height()` which takes as input $u_0$ and calculates $h$.
4. Calculate the couples ($u_0$, height($u_0$)) for $u_0 \leq 100$.

In [5]:
import math
import numpy as np
def suite(u):
    a=[u]
    while u!=1:
        if u%2==0:
            u=u//2
            a.append(u)
            
        else:
            u=u*3 + 1
            a.append(u)
        if a[-3:]==[4,2,1]:
            print("the sequence entered in the cycle of 4,2,1")
            return a
n=int(input("enter an integer: "))        
h=suite(n)
print(h)  
 
    
    
    

    
    

    
    

enter an integer: 12
tha sequence entered in the cycle of 4,2,1
[12, 6, 3, 10, 5, 16, 8, 4, 2, 1]


## Exercise 3: 

We consider the application $\sigma = \mathbb{N^*} \to \mathbb{N^*}$ which associates with each integer $n$ the sum of the cubes of the digits of its writing in base 10. 
- For example, if $n = 123$ then $\sigma(n) = 1^3 + 2^3 + 3^3 = 36$.

1. Write a `sigma()` function that takes as input a non-zero integer $n$ and returns the sum of cubes of its digits in base 10.

2. Find all integers $n \leq 1000$ such that $\sigma(n) = n$.

3. Given $a \in \mathbb{N^*}$, we are interested in the sequence ($u_n(a)$) defined by $u_0(a) = a$ and $u_{n+1}(a) = \sigma(u_n(a))$.

4. For several values of a, display the first 20 terms of the sequence ($u_n(a)$).

5. Show using the computer that for all $1 \leq a \leq 9999$ which is a multiple of 3 we have $u_{13}(a) = 153$.

In [9]:
import math
def sigma(n):
    count=0
    for i in str(n):
        j=int(i)
        count+=j
    return count
    for n in range(0,1000+1):
        l=[]
        if n==count:
            l.append(n)
            print(l)
        return l
op=[]
for i in range(1,1000+1):
    if i==sigma(i):
        op.append(i)
print(op)
print(sigma(55))



    
    
    
 
        
            
        

[1, 2, 3, 4, 5, 6, 7, 8, 9]
10


## Exercise 4: 

We call magic square of order n, any square matrix $M$ of order $n$ whose elements are the integers from 1 to $n^2$ arranged so that their sums on each line, on each column and on the two diagonals are equal. The common value of these sums is called the magic constant of $M$, and we have in fact $M = \frac{n(n^2+1)}{2}$.

1. Write a `permutation()` function that takes an array $T$ consisting of $n$ integers and decides if $T$ is a permutation of {1, 2, $\dots$ , n}.
    - We will first check if all the elements of $T$ are in {1, 2,$\dots$, n}.
    - Then we will check that no element of $T$ is repeated.
    
2. Write a function `magic_square()` which makes it possible to decide if a square matrix $M$ is a magic square.
    - We will first start by checking if the array M.flatten() is a permutation of {1, 2, $\dots$ , $n^2$}.
    - We will then use slicing to check if the sums of rows, columns and the two diagonals are the same.
    
3. Using the `magic_square()` function find the magic squares of order 2.

## Exercise 5:

1. Randomly generate a matrix $M$ of real numbers. Then calculate the tables of means, variances and standard deviations of the lines of $M$.

2. Doing a search, find numpy functions and methods to do the same job as in question 1. without using loops.

In [1]:
import math
import numpy as np
matrix=np.random.randint(1,8,(3,3))
print(matrix)
print("the tables of mean of each row:")
l=[]
l1=[]
for j in matrix :
    me=sum(j)/len(j) 
    print(me)
    variances = sum((i - me) ** 2 for i in j) / len(j)
    l.append(variances)
    l1.append(math.sqrt(variances))
print("the variances of each row:")
print(l)
print("the standard deviation of each row:")
print(l1)

#with numpy

means = np.mean(matrix, axis=1)
var = np.var(matrix, axis=1)
sta = np.std(matrix, axis=1)
print(means,var,sta)


    
     
    
    
    
       
 

        


[[5 5 5]
 [2 6 6]
 [6 6 1]]
the tables of mean of each row:
5.0
4.666666666666667
4.333333333333333
the variances of each row:
[0.0, 3.5555555555555554, 5.5555555555555545]
the standard deviation of each row:
[0.0, 1.8856180831641267, 2.357022603955158]
[5.         4.66666667 4.33333333] [0.         3.55555556 5.55555556] [0.         1.88561808 2.3570226 ]


## Execise 6:

A square matrix $M$ of order $n$ is said to be stochastic if all its coefficients are in [0,1] and the sum of the coefficients of each row of $M$ is equal to 1.

1. Write a test function `stoch()` which verifies if a square matrix $M$ is stochastic.
2. Write a function `stoch(n)` which allows to randomly generate a stochastic matrix of order $n$.
3. Write a `sequence()` function which takes as input a stochastic matrix $M$ of order $n$ and a vector $V$ of size $n$ as well as an integer $d$ and displays the vectors

$$
V, M.V, M^2.V, \dots , M^d.V
$$

- To calculate the product $M.V$ we use the `dot()` function by simply writing ```np.dot(M,V)```.

4. For fixed $n$, for example 4, randomly generate a stochastic matrix $M$ of order $n$ and a vector of size $n$. Then test the function `sequence()` on $M$ and $V$ with several values of $d$. Repeat this experiment several times and draw a conclusion.

In [ ]:
# Your code here